//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAccount
    {
        public int AccountID { get; set; }
        public string TradeCategory { get; set; }
        public string DatabaseName { get; set; }
        public string Category { get; set; }
        public string ShortName { get; set; }
        public string ManagementShortName { get; set; }
        public string TreasuryBook { get; set; }
    }
}
