//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPositionspm
    {
        public Nullable<System.DateTime> DateOfData { get; set; }
        public string OustPending { get; set; }
        public string BookName { get; set; }
        public string CtpyCode { get; set; }
        public string TradeRef { get; set; }
        public string BorrowLoan { get; set; }
        public string Cusip { get; set; }
        public string Ticker { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<double> LoanValue { get; set; }
        public Nullable<double> Rate { get; set; }
        public string TradeCategory { get; set; }
        public string CollTypeInd { get; set; }
        public string TradeCollateral { get; set; }
        public string PostTransType { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<System.DateTime> SettleDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public Nullable<double> PrePayRate { get; set; }
        public int PositionsID { get; set; }
        public Nullable<int> CTPYID { get; set; }
        public Nullable<int> QtyToProcess { get; set; }
        public Nullable<int> QtyProcessed { get; set; }
        public string CtpyMajor { get; set; }
        public string Security { get; set; }
        public string CodeType { get; set; }
        public string XRef { get; set; }
        public string Quick { get; set; }
        public string Sedol { get; set; }
        public string SecurityClass { get; set; }
        public string Issuer { get; set; }
        public string SecurityDesc { get; set; }
        public string LoanValueCurrency { get; set; }
        public string DealerID { get; set; }
        public string FirstLastDay { get; set; }
        public string SecSettleMode { get; set; }
        public string DvpInd { get; set; }
        public bool Callable { get; set; }
        public string Finder { get; set; }
        public Nullable<double> FRate { get; set; }
        public Nullable<double> DividendReq { get; set; }
        public string LoanReturn { get; set; }
        public string SettledFlag { get; set; }
        public Nullable<double> MarketValue { get; set; }
        public string LinkRef { get; set; }
        public string PricingCurr { get; set; }
        public string FailCode { get; set; }
        public string InternalComment { get; set; }
        public string ExternalComment { get; set; }
        public bool LongInventory { get; set; }
        public string PLComments { get; set; }
        public Nullable<decimal> InitialValue { get; set; }
        public Nullable<decimal> InitialQuantity { get; set; }
        public string RecalledInd { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public Nullable<double> PnLLoanValue { get; set; }
        public Nullable<double> SecurityClosingPrice { get; set; }
        public bool OrdAdrConverts { get; set; }
        public string PnLCurrencyValue { get; set; }
        public Nullable<int> DatabaseId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> CollReqMargin { get; set; }
        public string LegalEntity { get; set; }
    }
}
